{"name": "test_calculator", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestCalculator' object has no attribute 'driver'", "trace": "self = <test_02_calc.TestCalculator object at 0x0000023F0E983D90>\n\n    def test_calculator(self):\n>       calculator = CalculatorActions(self.driver)\nE       AttributeError: 'TestCalculator' object has no attribute 'driver'\n\ntest_02_calc.py:12: AttributeError"}, "start": 1744819918105, "stop": 1744819918105, "uuid": "95e87878-d8ea-40c4-852e-e4a849d4e771", "historyId": "f6e263a0a1643a021e0d2213c88b5a99", "testCaseId": "f6e263a0a1643a021e0d2213c88b5a99", "fullName": "test_02_calc.TestCalculator#test_calculator", "labels": [{"name": "suite", "value": "test_02_calc"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Networking2024"}, {"name": "thread", "value": "8352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_calc"}]}